//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RossaryApp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RossaryApp.Translations", typeof(Translations).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I believe in God, the Father almighty, Creator of heaven and earth, and in Jesus Christ, His only Son, our Lord, who was conceived by the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died and was buried; He descended into hell; on the third day He rose again from the dead; He ascended into heaven, and is seated at the right hand of God the Father almighty; from there He will come to judge the living and the dead. I believe in the Holy Spirit, the holy catholic Church,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChapletOfTheDivineMercy_ApostlesCreed {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_ApostlesCreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal God, in whom mercy is endless and the treasury of compassion — inexhaustible, look kindly upon us and increase Your mercy in us, that in difficult moments we might not despair nor become despondent, but with great confidence submit ourselves to Your holy will, which is Love and Mercy itself..
        /// </summary>
        internal static string ChapletOfTheDivineMercy_ClosingPrayer {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_ClosingPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hail Mary, full of grace. The Lord is with thee. Blessed art thou amongst women, and blessed is the fruit of thy womb, Jesus. Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death, Amen..
        /// </summary>
        internal static string ChapletOfTheDivineMercy_HailMary {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_HailMary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world..
        /// </summary>
        internal static string ChapletOfTheDivineMercy_HolyGod {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_HolyGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Father, Who art in heaven, hallowed be Thy name; Thy kingdom come; Thy will be done on earth as it is in heaven. Give us this day our daily bread; and forgive us our trespasses as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil, Amen..
        /// </summary>
        internal static string ChapletOfTheDivineMercy_OurFather {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_OurFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the sake of His sorrowful Passion, have mercy on us and on the whole world..
        /// </summary>
        internal static string ChapletOfTheDivineMercy_SmallBeads {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_SmallBeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Father, I offer you the Body and Blood, Soul and Divinity of Your Dearly Beloved Son, Our Lord, Jesus Christ, in atonement for our sins and those of the whole world..
        /// </summary>
        internal static string ChapletOfTheDivineMercy_TheEternalFather {
            get {
                return ResourceManager.GetString("ChapletOfTheDivineMercy_TheEternalFather", resourceCulture);
            }
        }
    }
}
